Repository TheAlgorithms/Julia, pull requests merged in 2021-07, with the labels that each got.

#55 Add anagrams in strings
  src/TheAlgorithms.jl
  src/strings/detect_anagrams.jl
  src/strings/is_palindrome.jl
  test/runtests.jl
  test/strings.jl
Labels: enhancement

#64 Contribution guidelines
  CONTRIBUTING.md
Labels: documentation, enhancement

#67 Clean dependencies
  Project.toml
  src/TheAlgorithms.jl
  test/Project.toml
  test/math.jl
  test/runtests.jl
  test/statistics.jl
Labels: enhancement

#70 feat: Add the `Approved label` workflow
  .github/workflows/approved-label.yml
Labels: enhancement

#69 add combinations and permutations
  src/TheAlgorithms.jl
  src/math/combination.jl
  src/math/permutation.jl
  test/math.jl
Labels: approved, enhancement

#74 implement new sorting algorithm- counting sort
  src/TheAlgorithms.jl
  src/sorts/counting_sort.jl
  test/sorts.jl
Labels: approved
