Repository TheAlgorithms/Julia, pull requests merged in 2021-06, with the labels that each got.

#1 README.md
  README.md
Labels: enhancement

#3 Add Linear Search
  searches/linear_search.jl
Labels: approved, enhancement

#4 Math folder
  math/area_under_curve.jl
  math/collatz_sequence.jl
  math/euler_method.jl
  math/line_length.jl
Labels: enhancement

#8 added project-rosalind folder and some starter
  project-rosalind/count_nucleotide.jl
  project-rosalind/dna2rna.jl
Labels: enhancement

#5 Create OLS.jl
  maths/sir.jl
  statistics/ordinary_least_squares.jl
Labels: enhancement

#9 added reverse complement
  project-rosalind/reverse_complement.jl
Labels: enhancement

#10 Add binary search
  searches/binary_search.jl
Labels: enhancement

#13 Make the repository a Julia package
  .github/workflows/CI.yml
  .github/workflows/CompatHelper.yml
  .github/workflows/TagBot.yml
  .gitignore
  LICENSE
  Project.toml
  README.md
  docs/Project.toml
  docs/make.jl
  docs/src/index.md
  math/sir_model.jl
  matrix/determinant.jl
  src/TheAlgorithms.jl
  src/math/area_under_curve.jl
  src/math/collatz_sequence.jl
  src/math/euler_method.jl
  src/math/line_length.jl
  src/math/sir_model.jl
  src/matrix/determinant.jl
  src/matrix/lu_decompose.jl
  src/project-rosalind/count_nucleotide.jl
  src/project-rosalind/dna2rna.jl
  src/project-rosalind/reverse_complement.jl
  src/searches/binary_search.jl
  src/searches/linear_search.jl
  src/statistics/ordinary_least_squares.jl
  statistics/ordinary_least_squares.jl
  test/math.jl
  test/matrix.jl
  test/project-rosalind.jl
  test/runtests.jl
  test/searches.jl
  test/statistics.jl
Labels: enhancement

#21 Variance by Pearson method
  src/statistics/variance.jl
Labels: enhancement

#22 test file of variance.jl
  test/variance.jl
Labels: enhancement

#27 Some more math functions
  src/TheAlgorithms.jl
  src/math/abs.jl
  src/math/area.jl
  src/math/ceil_floor.jl
  test/math.jl
Labels: enhancement

#31 added Pearson correlation function
  src/TheAlgorithms.jl
  src/statistics/PearsonCorrelaion.jl
  test/PearsonCorrelation.jl
Labels: enhancement

#32 Fix a lot of small things
  CONTRIBUTING.md
  Project.toml
  src/TheAlgorithms.jl
  src/knapsack/knapsack.jl
  src/math/abs.jl
  src/math/area.jl
  src/math/area_under_curve.jl
  src/math/armstrong_number.jl
  src/math/average_median.jl
  src/math/average_mode.jl
  src/math/ceil_floor.jl
  src/math/collatz_sequence.jl
  src/math/euler_method.jl
  src/math/line_length.jl
  src/math/sir_model.jl
  src/matrix/determinant.jl
  src/matrix/lu_decompose.jl
  src/project-rosalind/count_nucleotide.jl
  src/project-rosalind/dna2rna.jl
  src/project-rosalind/reverse_complement.jl
  src/scheduling/fcfs.jl
  src/searches/binary_search.jl
  src/searches/exponential_search.jl
  src/searches/interpolation_search.jl
  src/searches/jump_search.jl
  src/searches/linear_search.jl
  src/statistics/PearsonCorrelaion.jl
  src/statistics/ordinary_least_squares.jl
  src/statistics/pearson_correlation.jl
  src/statistics/variance.jl
  src/strings/is_palindrome.jl
  test/PearsonCorrelation.jl
  test/knapsack.jl
  test/math.jl
  test/project-rosalind.jl
  test/scheduling.jl
  test/searches.jl
  test/statistics.jl
  test/strings.jl
  test/variance.jl
Labels: bug, documentation, enhancement

#52 added monte carlo integration
  src/TheAlgorithms.jl
  src/math/monte_carlo_integration.jl
  test/math.jl
Labels: enhancement

#66 Document variance
  src/statistics/variance.jl
  test/statistics.jl
Labels: bug, documentation
