Repository TheAlgorithms/Julia, pull requests merged in 2022-10, with the labels that each got.

#145 Added fibonacci series generators (recursive, recursive with memo, iterative)
  src/TheAlgorithms.jl
  src/math/fibonacci.jl
  test/math.jl
Labels: enhancement

#146 Added Mersenne Primes
  src/TheAlgorithms.jl
  src/math/eulers_totient.jl
  src/math/mersenne_prime.jl
  test/math.jl
Labels: enhancement

#147 feat: add a Gitpod Dockerfile
  .gitpod.dockerfile
  .gitpod.yml
  Project.toml
  docs/src/index.md
  src/TheAlgorithms.jl
  src/math/fibonacci.jl
Labels: enhancement, approved

#151 Added Catalan Number function
  src/TheAlgorithms.jl
  src/math/catalan_number.jl
  test/math.jl
Labels: enhancement

#150 Added average absolute deviation
  src/TheAlgorithms.jl
  src/math/average_absolute_deviation.jl
  test/math.jl
Labels: enhancement

#149 Added bogo sort
  src/TheAlgorithms.jl
  src/sorts/bogo_sort.jl
  test/sorts.jl
Labels: enhancement

#154 chore: add codeowners file
  docs/CODEOWNERS
Labels: enhancement, invalid

#153 Added Solution to Project Euler Problem 001
  src/TheAlgorithms.jl
  src/project-euler/problem_001.jl
  test/project-euler.jl
  test/runtests.jl
Labels: enhancement

#155 Added Solution to Project Euler Problem 002
  src/TheAlgorithms.jl
  src/project-euler/problem_002.jl
  test/project-euler.jl
Labels: enhancement

#157 feat: run formatter workflow on PRs
  .github/workflows/format.yml
Labels: enhancement, invalid, approved

#161 Added solution to Project Euler problem 007
  src/TheAlgorithms.jl
  src/project-euler/problem_007.jl
  test/project-euler.jl
Labels: enhancement

#162 fix: `.gitpod.dockerfile` issues
  .gitpod.dockerfile
Labels: bug

#163 feat: improve the Julia formatter workflow
  .github/workflows/format.yml
Labels: enhancement

#165 docs: improve the contributing guidelines
  CONTRIBUTING.md
Labels: documentation
